name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
        gemfile: ["gemfiles/rails6.gemfile"]
        include:
        - ruby: "2.6"
          gemfile: "gemfiles/rails5.gemfile"
        - ruby: "2.7"
          gemfile: "gemfiles/rails6.gemfile"
        - ruby: "3.1"
          gemfile: "gemfiles/railsmaster.gemfile"
        - ruby: "3.0"
          gemfile: "gemfiles/rails70.gemfile"
    services:
      redis:
        image: redis:5.0-alpine
        ports: ["6379:6379"]
        options: --health-cmd="redis-cli ping" --health-interval 1s --health-timeout 3s --health-retries 30
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: |
        bundle exec rake
